version: '2.4'

services:
  team-robocin:
    image: robocin/ssl:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
      VNC_RESOLUTION: 1920x1080
    volumes:
      - team-robocin-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-robofei:
    image: bollos00/robofeissl-ssl-strategy:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-robofei-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-uroborus:
    image: registry.wr.sc.usp.br/uroborus
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-uroborus-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-roboime:
    image: roboime/robocup2021:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-roboime-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-omid:
    image: robocupssl/omid:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-omid-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-warthog:
    image: registry.wr.sc.usp.br/wrlarc2021:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-omid-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-maracatronics:
    image: registry.wr.sc.usp.br/maracatronics-ssl:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-maracatronics-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-itandroids:
    image: robocupssl/ubuntu-vnc:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-omid-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-uaisoccer:
    image: registry.wr.sc.usp.br/uaisystem:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-omid-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-roboforge:
    image: robocupssl/ubuntu-vnc:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-omid-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole


volumes:
  team-robocin-data:
  team-robofei-data:
  team-uroborus-data:
  team-roboime-data:
  team-omid-data:
  team-warthog-data:
  team-maracatronics-data:
  team-itandroids-data:
  team-uaisoccer-data:
  team-roboforge-data:


networks:
  match:
  guacamole:
